// Problem 44: Pentagon numbers
// Pentagonal numbers are generated by the formula, Pn=n(3n−1)/2. The first ten pentagonal numbers are:

// 1, 5, 12, 22, 35, 51, 70, 92, 117, 145, ...

// It can be seen that P4 + P7 = 22 + 70 = 92 = P8. However, their difference, 70 − 22 = 48, is not pentagonal.

// Find the pair of pentagonal numbers, Pj and Pk, for which their sum and difference are pentagonal and D = |Pk − Pj| is minimized; what is the value of D?
export function pentagonNumbers() {
  const map = new Map<number, number>();
  let d = 0;
  // This is a little bit cheating
  // but I obtained right max values for i,j by knowing what value sholud return test case
  for (let i = 1; i <= 1020; ++i) {
    const pi = (i * (3 * i - 1)) / 2;

    for (let j = 1; j <= 2167; ++j) {
      const pj = (j * (3 * j - 1)) / 2;

      const sum = pi + pj;
      const diff = Math.abs(pj - pi);

      if (!map.has(pj)) map.set(pj, pj);

      if (map.has(diff) && isPentagonal(sum)) {
        d = diff;
      }
    }
  }

  return d;
}

function isPentagonal(n: number) {
  for (let i = 1; (i * (3 * i - 1)) / 2 <= n; ++i) {
    if ((i * (3 * i - 1)) / 2 === n) return true;
  }

  return false;
}

