// Problem 45: Triangular, pentagonal, and hexagonal
// Triangle, pentagonal, and hexagonal numbers are generated by the following formulae:

// Triangle
// Tn=n(n+1)/2
// 1, 3, 6, 10, 15, ...

// Pentagonal
// Pn=n(3n−1)/2
// 1, 5, 12, 22, 35, ...

// Hexagonal
// Hn=n(2n−1)
// 1, 6, 15, 28, 45, ...
// It can be verified that T285 = P165 = H143 = 40755.

// Find the next triangle number that is also pentagonal and hexagonal.
export function triPentaHexa(n: number) {
  const pentagonalMap = new Map<number, number>();
  const hexagonalMap = new Map<number, number>();

  let tn = 286;
  let pn = 166;
  let hn = 144;

  while (pn <= 50000 && hn <= 50000) {
    const pent = (pn * (3 * pn - 1)) / 2;
    const hex = hn * (2 * hn - 1);

    pentagonalMap.set(pent, pent);
    hexagonalMap.set(hex, hex);

    ++pn;
    ++hn;
  }

  while (true) {
    const tri = (tn * (tn + 1)) / 2;

    if (pentagonalMap.has(tri) && hexagonalMap.has(tri)) {
      return tri;
    }

    ++tn;
  }
}

